name: Deploy static playlists

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */2 * * *'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Copy playlists to root
        run: |
          cp -R lists/* .

      - name: Create .nojekyll
        run: touch .nojekyll

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: .
          clean: true
